### PR TITLE
Autoboot support for WiiFlow via arguments. (Wiimpathy)

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
This modification adds WiiFlow compatibility (support) to WiiSX for autolaunch a PlayStation 1 game via arguments, from a .ini plugin config file or from arguments on the meta.xml.

Tested and working as expected.

### CODE REVIEW

**Comment by emukidid** [comment]
Sorry, there's some conflicts due to my recent push, can you please resolve them?

**Comment by saulfabregwiivc** [comment]
Sure i will fix the conflicts later.

**Comment by saulfabregwiivc** [comment]
Conflict solved, now you can merge my WiiFlow change.

**Comment by pcercuei** [comment]
Better rebase on top of master instead of merging the master branch...

**Comment by saulfabregwiivc** [comment]
That's a good idea, i will remerge my changes with latest master and i'll make a new PR. Closing this one.

**Comment by pcercuei** [comment]
Well you don't need to close the PR. Just rebase your commit on top of master, then force-push your `autoboot-wiiFlow` branch.

**Pull request closed without merging**
